name: CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  release_matrix:
    strategy:
      matrix:
        release: [stable, beta, nightly]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.release }}
          profile: minimal
          components: clippy, rustfmt
          override: true

      - name: Check Rust toolchain
        run: make toolchain

      - name: Format
        run: make format

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Binary Release
        run: make release

      # UNCOMMENT SECTION TO BUILD AND PUSH TO GHCR
      # - name: Lint Dockerfile
      #   uses: hadolint/hadolint@v2
      #   with:
      #     files: Dockerfile
      #     level: error

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Log in to GitHub container registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ github.token }}

      # - name: Lowercase the repo name and username
      #   run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
      # - name: Build and push container image to registry
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
      #     file: ./Dockerfile