name: CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
          
    - name: Install Rust toolchain
      run: make install

    - name: Check Rust toolchain
      run: make toolchain

    - name: Format
      run: make format

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Binary Release
      run: make release

    - name: Lint Dockerfile
      uses: jbergstroem/hadolint-gh-action@v1
      with:
        dockerfile: Dockerfile
        error_level: -1 # Only log errors do not fail req. for cc/distroless :latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Lowercase the repo name and username
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
        file: ./Dockerfile